# GoReleaser configuration for klaudiush
# See https://goreleaser.com for documentation
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: klaudiush

before:
  hooks:
    - go mod tidy

builds:
  - id: klaudiush
    main: ./cmd/klaudiush
    binary: klaudiush
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: checksums.txt
  algorithm: sha256

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  use: github
  sort: asc
  abbrev: -1
  groups:
    - title: Features
      regexp: ^.*feat(\([^)]*\))?:.*$
      order: 0
    - title: Bug Fixes
      regexp: ^.*fix(\([^)]*\))?:.*$
      order: 1
    - title: Documentation
      regexp: ^.*docs(\([^)]*\))?:.*$
      order: 2
    - title: CI/CD
      regexp: ^.*ci(\([^)]*\))?:.*$
      order: 3
    - title: Tests
      regexp: ^.*test(\([^)]*\))?:.*$
      order: 4
    - title: Refactoring
      regexp: ^.*refactor(\([^)]*\))?:.*$
      order: 5
    - title: Chores
      regexp: ^.*chore(\([^)]*\))?:.*$
      order: 6
    - title: Other
      order: 999
  filters:
    exclude:
      - '^Merge pull request'
      - '^Merge branch'

release:
  github:
    owner: smykla-labs
    name: klaudiush
  prerelease: auto
  draft: false
  name_template: 'v{{ .Version }}'
  header: |
    ## klaudiush v{{ .Version }}

    Claude Code hooks validator for enforcing git workflow standards and commit message conventions.
  footer: |
    ## Installation

    ### Using install script (recommended)
    ```bash
    curl -sSfL https://raw.githubusercontent.com/smykla-labs/klaudiush/main/install.sh | sh
    ```

    ### Manual download
    Download the appropriate archive for your platform from the assets below, extract, and add to your PATH.

    ### Checksums
    SHA256 checksums are available in `checksums.txt`.

    ---
    **Full Changelog**: https://github.com/smykla-labs/klaudiush/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap (optional - uncomment to enable)
# brews:
#   - repository:
#       owner: smykla-labs
#       name: homebrew-tap
#     directory: Formula
#     homepage: https://github.com/smykla-labs/klaudiush
#     description: Claude Code hooks validator
#     license: MIT
#     install: |
#       bin.install "klaudiush"
#     test: |
#       system "#{bin}/klaudiush", "--help"
