version: '3'

# Task runner configuration for claude-hooks
# Uses mise for tool version management
# Run 'mise install' before running tasks

vars:
  BINARY_NAME: claude-hooks
  INSTALL_PATH: ~/.claude/hooks/dispatcher

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary (without signoff validation)
    cmds:
      - mise exec -- go build -o bin/{{.BINARY_NAME}} ./cmd/claude-hooks
    sources:
      - '**/*.go'
    generates:
      - bin/{{.BINARY_NAME}}

  build:prod:
    desc: Build the binary with signoff validation (uses git config for signoff)
    vars:
      GIT_NAME:
        sh: git config user.name
      GIT_EMAIL:
        sh: git config user.email
      SIGNOFF: '{{.GIT_NAME}} <{{.GIT_EMAIL}}>'
    cmds:
      - |
        mise exec -- go build \
          -ldflags="-X 'github.com/smykla-labs/claude-hooks/internal/validators/git.ExpectedSignoff={{.SIGNOFF}}'" \
          -o bin/{{.BINARY_NAME}} \
          ./cmd/claude-hooks
    sources:
      - '**/*.go'
    generates:
      - bin/{{.BINARY_NAME}}

  test:
    desc: Run tests
    cmds:
      - mise exec -- go test -v -race -cover ./...

  test:unit:
    desc: Run unit tests only
    cmds:
      - mise exec -- go test -v -race -cover -short ./...

  test:integration:
    desc: Run integration tests only
    cmds:
      - mise exec -- go test -v -race -cover -run Integration ./...

  lint:
    desc: Run linters on all files
    cmds:
      - mise exec -- golangci-lint run

  lint:fix:
    desc: Run linters with auto-fix on all files
    cmds:
      - mise exec -- golangci-lint run --fix

  lint:staged:
    desc: Run linters on modified and staged files only
    vars:
      STAGED_FILES:
        sh: git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true
      MODIFIED_FILES:
        sh: git diff --name-only --diff-filter=ACM | grep '\.go$' || true
      ALL_CHANGED_FILES:
        sh: |
          (git diff --cached --name-only --diff-filter=ACM; git diff --name-only --diff-filter=ACM) | \
          grep '\.go$' | sort -u || true
    cmds:
      - |
        if [ -n "{{.ALL_CHANGED_FILES}}" ]; then
          echo "Linting changed files..."
          mise exec -- golangci-lint run {{.ALL_CHANGED_FILES}}
        else
          echo "No Go files to lint"
        fi

  check:
    desc: Alias for lint:fix
    cmds:
      - task: lint:fix

  fmt:
    desc: Format code
    cmds:
      - mise exec -- golangci-lint run --fix

  install:
    desc: Install binary to ~/.claude/hooks/
    deps:
      - build
    cmds:
      - mkdir -p ~/.claude/hooks
      - cp bin/{{.BINARY_NAME}} {{.INSTALL_PATH}}
      - chmod +x {{.INSTALL_PATH}}

  install:hooks:
    desc: Install git pre-commit hook
    cmds:
      - |
        if [ ! -d ".git" ]; then
          echo "Error: Not a git repository"
          exit 1
        fi
      - mkdir -p .git/hooks
      - cp .githooks/pre-commit .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "✓ Pre-commit hook installed to .git/hooks/pre-commit"

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf dist/
      - rm -rf build/
      - rm -rf tmp/

  deps:
    desc: Download dependencies
    cmds:
      - mise exec -- go mod download
      - mise exec -- go mod tidy

  verify:
    desc: Run all verification tasks
    cmds:
      - task: fmt
      - task: lint
      - task: test
